### ISSUE TITLE
“为什么小米” 会被转为 "为什幺小米"

### ISSUE THREAD

**Issue by Domi-Zhang** [gumblex/zhconv#2]
应该是zhcdit.json中定义了"么小"这个词。我现在的处理方式是将zhcdict.json拷出来，在"么小"前添加"为什么"，然后启动时手动load_dict

**Comment by gumblex** [comment]
我也没有办法。

可以在转换时指定 `update={'为什么小':'为什么小'}` 自定义词典覆盖。
