### ISSUE TITLE
MediaWiki 转换词典的版权问题

### ISSUE THREAD

**Issue by tiansh** [gumblex/zhconv#6]
MediaWiki 的代码是 GPL 的，他的转换词典有通过其他协议释出的版本吗？如果没有的话 MIT 协议的项目应该没法用他的词典。

**Comment by gumblex** [comment]
现在词典是从 ZhConversion.php（GPLv2+）转换的，加上 OpenCC（Apache v2）的单字转换数据。MediaWiki 数据确实有问题；单字转换数据本身不足以构成版权，所以不需要标注了。

已经发 v1.4.1 版本更正该问题：整体授权改为 GPLv2+，代码仍为 MIT。
